/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Generate the src/scapi/custom-clients.ts file from schema metadata sidecars.
 *
 * This file is purely declarative — it exports a type and a data array.
 * The actual client creation logic lives in src/lib/api-clients.ts.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { readAllSchemaMetadata } from './schema-utils';

const COPYRIGHT_HEADER = `/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */`;

/**
 * Generate the custom-clients.ts file in the template project.
 *
 * @param scapiDir - Absolute path to the src/scapi/ directory in the template project
 */
export function generateCustomClientsFile(scapiDir: string): void {
    const schemasDir = join(scapiDir, 'schemas');
    const entries = readAllSchemaMetadata(schemasDir);
    const customClientsPath = join(scapiDir, 'custom-clients.ts');

    if (entries.length === 0) {
        const content = `${COPYRIGHT_HEADER}

/**
 * Custom SCAPI Clients — generated by \`sfnext scapi\`, do not edit manually.
 *
 * Use \`sfnext scapi add --schema <file>\` to add a client from a local schema file.
 * Use \`sfnext scapi add <family> <name> <version>\` to pull from the SCAPI Schemas API.
 * Use \`sfnext scapi list\` to see registered custom clients.
 */
export { type Clients as AppClients } from '@salesforce/storefront-next-runtime/scapi';

export const customClients: never[] = [];
`;
        writeFileSync(customClientsPath, content, 'utf-8');
        return;
    }

    const imports: string[] = [];
    const typeEntries: string[] = [];
    const clientEntries: string[] = [];

    entries.forEach(({ clientKey, basePath, supportsLocale, orgPrefix, schemaName }, index) => {
        imports.push(
            `import type { paths as P${index} } from './generated/${schemaName}';`,
            `import { operations as ops${index} } from './generated/${schemaName}.operations';`
        );
        typeEntries.push(`    ${clientKey}: ProxyClient<Client<P${index}>, typeof ops${index}>;`);
        clientEntries.push(
            `    { key: '${clientKey}', basePath: '${basePath}', ops: ops${index}, locale: ${supportsLocale}, orgPrefix: ${orgPrefix} },`
        );
    });

    const content = `${COPYRIGHT_HEADER}

/**
 * Custom SCAPI Clients — generated by \`sfnext scapi\`, do not edit manually.
 */
import { type Client, type Clients, type MergeClients, type ProxyClient } from '@salesforce/storefront-next-runtime/scapi';

${imports.join('\n')}

export type AppClients = MergeClients<Clients, {
${typeEntries.join('\n')}
}>;

export const customClients = [
${clientEntries.join('\n')}
] as const;
`;

    writeFileSync(customClientsPath, content, 'utf-8');
}
