/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Generate the template's SCAPI surface from schema metadata sidecars:
 *
 * 1. `src/scapi/custom-clients.ts` — declarative registry: imports, `AppClients` type,
 *    and a `customClients` const array consumed by `src/lib/api-clients.server.ts`.
 * 2. `src/scapi/index.ts` — the template-local SCAPI barrel. Template code imports SCAPI
 *    types and clients from `@/scapi`; this barrel transparently re-exports the runtime
 *    SDK's surface and substitutes locally-generated namespaces for any overrides.
 * 3. `src/scapi/generated/<schemaName>.namespace.ts` — only emitted for overrides.
 *    Wraps the openapi-typescript output in a namespace whose shape (`endpoints`,
 *    `schemas`, `operations`) matches the runtime SDK so consumers don't change call sites.
 *
 * All three files are pure data + re-exports; safe to commit and conflict-resistant.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { isBuiltInClientKey, readAllSchemaMetadata, type SchemaMetadata } from './schema-utils';

const COPYRIGHT_HEADER = `/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */`;

/**
 * Mapping of every built-in client key to its runtime namespace name.
 * Camel→Pascal would suffice for all current entries, but keeping the map explicit
 * prevents surprises if a future client uses a name that doesn't round-trip cleanly.
 *
 * Keep in sync with `BUILT_IN_CLIENT_KEYS` in schema-utils.ts and the namespaces in
 * `packages/storefront-next-runtime/src/scapi-client/types.ts`.
 */
const BUILT_IN_NAMESPACE_BY_KEY: Record<string, string> = {
    shopperAvailability: 'ShopperAvailability',
    shopperBasketsV1: 'ShopperBasketsV1',
    shopperBasketsV2: 'ShopperBasketsV2',
    shopperConfigurations: 'ShopperConfigurations',
    shopperConsents: 'ShopperConsents',
    shopperContext: 'ShopperContext',
    shopperCustomers: 'ShopperCustomers',
    shopperExperience: 'ShopperExperience',
    shopperGiftCertificates: 'ShopperGiftCertificates',
    shopperLogin: 'ShopperLogin',
    shopperOrders: 'ShopperOrders',
    shopperPayments: 'ShopperPayments',
    shopperProducts: 'ShopperProducts',
    shopperPromotions: 'ShopperPromotions',
    shopperSearch: 'ShopperSearch',
    shopperSeo: 'ShopperSeo',
    shopperStores: 'ShopperStores',
};

type Entry = SchemaMetadata & { schemaName: string };

function isOverride(entry: Entry): boolean {
    return (entry.kind ?? (isBuiltInClientKey(entry.clientKey) ? 'override' : 'custom')) === 'override';
}

/**
 * Write `src/scapi/custom-clients.ts` from the schema entries.
 * Always writes — empty registry produces a no-op file.
 */
function writeCustomClientsFile(scapiDir: string, entries: Entry[]): void {
    const customClientsPath = join(scapiDir, 'custom-clients.ts');

    if (entries.length === 0) {
        const content = `${COPYRIGHT_HEADER}

/**
 * Custom SCAPI Clients — generated by \`sfnext scapi\`, do not edit manually.
 *
 * Use \`sfnext scapi add --schema <file>\` to add a client from a local schema file.
 * Use \`sfnext scapi add <family> <name> <version>\` to pull from the SCAPI Schemas API.
 * Use \`sfnext scapi list\` to see registered clients.
 */
export { type Clients as AppClients } from '@salesforce/storefront-next-runtime/scapi';

export const customClients: never[] = [];
`;
        writeFileSync(customClientsPath, content, 'utf-8');
        return;
    }

    const imports: string[] = [];
    const typeEntries: string[] = [];
    const clientEntries: string[] = [];

    entries.forEach(({ clientKey, basePath, supportsLocale, orgPrefix, schemaName }, index) => {
        imports.push(
            `import type { paths as P${index} } from './generated/${schemaName}';`,
            `import { operations as ops${index} } from './generated/${schemaName}.operations';`
        );
        typeEntries.push(`    ${clientKey}: ProxyClient<Client<P${index}>, typeof ops${index}>;`);
        clientEntries.push(
            `    { key: '${clientKey}', basePath: '${basePath}', ops: ops${index}, locale: ${supportsLocale}, orgPrefix: ${orgPrefix} },`
        );
    });

    const content = `${COPYRIGHT_HEADER}

/**
 * Custom SCAPI Clients — generated by \`sfnext scapi\`, do not edit manually.
 */
import { type Client, type Clients, type MergeClients, type ProxyClient } from '@salesforce/storefront-next-runtime/scapi';

${imports.join('\n')}

export type AppClients = MergeClients<Clients, {
${typeEntries.join('\n')}
}>;

export const customClients = [
${clientEntries.join('\n')}
] as const;
`;

    writeFileSync(customClientsPath, content, 'utf-8');
}

/**
 * Write a per-override namespace wrapper that mirrors the shape of the runtime's
 * namespaces in `packages/storefront-next-runtime/src/scapi-client/types.ts`.
 * Only emitted when the entry overrides a built-in client.
 */
function writeOverrideNamespaceFile(scapiDir: string, entry: Entry): void {
    const namespaceName = BUILT_IN_NAMESPACE_BY_KEY[entry.clientKey];
    if (!namespaceName) return;

    const generatedDir = join(scapiDir, 'generated');
    mkdirSync(generatedDir, { recursive: true });
    const filePath = join(generatedDir, `${entry.schemaName}.namespace.ts`);
    const content = `${COPYRIGHT_HEADER}

/* eslint-disable @typescript-eslint/no-namespace, import/no-namespace */
/**
 * Override namespace for \`${namespaceName}\` — generated by \`sfnext scapi\`, do not edit manually.
 *
 * Mirrors the shape of the runtime SDK's namespace so consumers of \`@/scapi\` see the
 * same \`endpoints\`, \`schemas\`, and \`operations\` keys, but resolved against the local
 * schema (e.g., with \`c_*\` custom attributes typed).
 */
import type * as Source from './${entry.schemaName}';

export namespace ${namespaceName} {
    export type endpoints = Source.paths;
    export type schemas = Source.components['schemas'];
    export type operations = Source.operations;
}
`;
    writeFileSync(filePath, content, 'utf-8');
}

/**
 * Write `src/scapi/index.ts` — the template-local SCAPI barrel.
 *
 * Always wildcards the runtime SCAPI surface so future SDK additions flow through
 * automatically. Overridden namespaces are re-exported explicitly below the wildcard;
 * ECMAScript module semantics make a named re-export shadow a same-named wildcard
 * re-export, so consumers of `@/scapi` see the local generated namespace for overridden
 * clients and the runtime version for everything else.
 */
function writeBarrelFile(scapiDir: string, entries: Entry[]): void {
    const indexPath = join(scapiDir, 'index.ts');
    const overrides = entries.filter(isOverride);

    if (overrides.length === 0) {
        const content = `${COPYRIGHT_HEADER}

/**
 * Template-local SCAPI barrel — generated by \`sfnext scapi\`, do not edit manually.
 *
 * Template code should import SCAPI types and clients from \`@/scapi\` (this file) so
 * that any overrides registered via \`sfnext scapi add\` resolve to local schemas. With
 * no overrides registered this is a transparent re-export of the runtime SDK.
 */
export * from '@salesforce/storefront-next-runtime/scapi';
export { customClients, type AppClients } from './custom-clients';
`;
        writeFileSync(indexPath, content, 'utf-8');
        return;
    }

    const overriddenNamespaces = overrides
        .map((e) => BUILT_IN_NAMESPACE_BY_KEY[e.clientKey])
        .filter((n): n is string => typeof n === 'string');

    const overrideExports = overrides
        .map((e) => {
            const ns = BUILT_IN_NAMESPACE_BY_KEY[e.clientKey];
            return ns ? `export type { ${ns} } from './generated/${e.schemaName}.namespace';` : '';
        })
        .filter(Boolean)
        .join('\n');

    const content = `${COPYRIGHT_HEADER}

/**
 * Template-local SCAPI barrel — generated by \`sfnext scapi\`, do not edit manually.
 *
 * Wildcard re-exports the runtime SCAPI surface; the explicit named re-exports below
 * shadow the wildcard so each active override resolves to its locally-generated schema.
 *
 * Active overrides: ${overriddenNamespaces.join(', ')}
 */
export * from '@salesforce/storefront-next-runtime/scapi';

// Overridden namespaces — resolved against local schemas
${overrideExports}

// Custom client registry consumed by api-clients.server.ts
export { customClients, type AppClients } from './custom-clients';
`;
    writeFileSync(indexPath, content, 'utf-8');
}

/**
 * Generate the template's SCAPI surface (`custom-clients.ts`, `index.ts`, and any
 * per-override namespace wrappers) from `.meta.json` sidecars in `schemas/`.
 *
 * @param scapiDir - Absolute path to the src/scapi/ directory in the template project
 */
export function generateCustomClientsFile(scapiDir: string): void {
    const schemasDir = join(scapiDir, 'schemas');
    const entries = readAllSchemaMetadata(schemasDir);

    writeCustomClientsFile(scapiDir, entries);
    writeBarrelFile(scapiDir, entries);

    for (const entry of entries) {
        if (isOverride(entry)) {
            writeOverrideNamespaceFile(scapiDir, entry);
        }
    }
}
