import { registry } from '@/lib/registry';

// STATIC_REGISTRY_START

/* eslint-disable */
/**
 * Initialize the static component registry.
 * This function is auto-generated by the staticRegistry Vite plugin.
 * 
 * DO NOT EDIT THIS FUNCTION MANUALLY - it will be overwritten on next build.
 * 
 * Components registered: odyssey_base.contentCard, odyssey_base.grid, odyssey_base.hero, odyssey_base.heroCarousel, odyssey_base.popularCategories, odyssey_base.popularCategory, odyssey_base.productCarousel
 */
export function initializeRegistry(targetRegistry = registry): void {
    targetRegistry.registerImporter('odyssey_base.contentCard', () => import('../components/content-card/index'));
    targetRegistry.registerImporter('odyssey_base.grid', () => import('../components/grid/index'));
    targetRegistry.registerImporter('odyssey_base.hero', () => import('../components/hero/index'));
    targetRegistry.registerImporter('odyssey_base.heroCarousel', () => import('../components/hero-carousel/index'));
    targetRegistry.registerImporter('odyssey_base.popularCategories', () => import('../components/home/popular-categories/index'), { loader: 'loader', clientLoader: 'clientLoader' });
    targetRegistry.registerImporter('odyssey_base.popularCategory', () => import('../components/home/popular-category/index'), { loader: 'loader', clientLoader: 'clientLoader' });
    targetRegistry.registerImporter('odyssey_base.productCarousel', () => import('../components/product-carousel/index'), { loader: 'loader', fallback: 'fallback' });
}

// STATIC_REGISTRY_END
