/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import type { Plugin, ResolvedConfig } from 'vite';
import path from 'path';
import fs from 'fs-extra';
import { fileURLToPath } from 'url';
import { getMrtEntryFile } from '../mrt/utils';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * This is a Vite plugin specifically for building the Managed Runtime production bundle.
 * This plugin relies on the @react-router/dev/vite plugin to work.
 * This plugin creates the Managed Runtime production bundle from the build output of the @react-router/dev/vite plugin.
 *
 * @returns {Plugin} A Vite plugin for building the Managed Runtime production react-router bundle
 */
export const managedRuntimeBundlePlugin = (): Plugin => {
    let resolvedConfig: ResolvedConfig;

    // Note: The react-router vite plugin does not use/respect vite's config.build.outDir
    // We must not use the resolvedConfig.build.outDir
    // Instead, react-router has a "buildDirectory" option from react-router.config.ts
    // Should we infer the build directory from the react-router config OR let the user configure it?
    let buildDirectory: string;

    /**
     * Creates the Managed Runtime production bundle assets
     * - ssr.mjs or streamingHandler.mjs
     * - loader.js
     * - package.json
     *
     * @returns {Promise<void>}
     */
    const createManagedRuntimeBundleAssets = async (): Promise<void> => {
        const loaderPath = path.resolve(buildDirectory, 'loader.js');
        // TODO: Move the MRT_BUNDLE_TYPE env var to a command line option with sfnext
        const mrtEntryFile = `${getMrtEntryFile(resolvedConfig?.mode)}.mjs`;
        const mrtEntryPath = path.resolve(buildDirectory, mrtEntryFile);

        await fs.ensureDir(buildDirectory);
        await fs.outputFile(loaderPath, '// This file is intentionally empty');

        const prebuiltMrtEntryPath = path.resolve(__dirname, `./mrt/${mrtEntryFile}`);
        await fs.copy(prebuiltMrtEntryPath, mrtEntryPath);

        // Copy source map for MRT entry point (if available)
        const prebuiltMrtEntryMapPath = `${prebuiltMrtEntryPath}.map`;
        if (await fs.pathExists(prebuiltMrtEntryMapPath)) {
            await fs.copy(prebuiltMrtEntryMapPath, `${mrtEntryPath}.map`);
        }

        // Copy shared chunks generated by the build process
        // These are identified by the 'sfnext-server-' prefix
        const mrtDir = path.resolve(__dirname, './mrt');
        if (await fs.pathExists(mrtDir)) {
            const files = await fs.readdir(mrtDir);
            for (const file of files) {
                if (file.startsWith('sfnext-server-') && file.endsWith('.mjs')) {
                    await fs.copy(path.join(mrtDir, file), path.resolve(buildDirectory, file));
                    // Copy source map for shared chunk (if available)
                    const mapFile = `${file}.map`;
                    if (files.includes(mapFile)) {
                        await fs.copy(path.join(mrtDir, mapFile), path.resolve(buildDirectory, mapFile));
                    }
                }
            }
        }

        const packageJsonPath = path.resolve(resolvedConfig.root, 'package.json');
        const buildPackageJsonPath = path.resolve(buildDirectory, 'package.json');

        const packageJson = await fs.readJson(packageJsonPath);

        // Currently MRT only supports CJS modules, and we are building a CJS bundle.
        // But we need to make sure the package.json doesn't have the "type" key to use ESM
        // otherwise the MRT environment will break because the node ESM resolution will not work
        // for our CJS bundle.
        delete packageJson.type;
        await fs.writeJson(buildPackageJsonPath, packageJson, { spaces: 2 });
    };

    return {
        name: 'storefront-next:managed-runtime-bundle',
        apply: 'build',
        config({ mode }) {
            return {
                build: {
                    rollupOptions: {
                        // Suppress benign sourcemap warnings emitted by Rollup during
                        // the transform phase. These occur when Rollup tries to trace a
                        // warning's location back through the sourcemap chain but the
                        // intermediate sourcemaps (from TypeScript, Tailwind, etc.)
                        // don't map position (1:0). The warnings are purely cosmetic —
                        // actual sourcemaps in the build output are unaffected.
                        //
                        // This is the same approach used by @vitejs/plugin-react (PR #369)
                        // and @react-router/dev's plugin.
                        // See: https://github.com/vitejs/vite-plugin-react/pull/369
                        // See: https://github.com/vitejs/vite/issues/15012
                        onLog(level, log, defaultHandler) {
                            if (log.code === 'SOURCEMAP_ERROR' && log.message.includes('resolve original location')) {
                                return;
                            }
                            defaultHandler(level, log);
                        },
                    },
                },
                environments: {
                    ssr: {
                        resolve: {
                            noExternal: true,
                        },
                    },
                },
                experimental: {
                    // MRT serves each deploy's bundle under a per-deploy prefix:
                    //     {MRT_ENV_BASE_PATH}/mobify/bundle/{BUNDLE_ID}/client/...
                    // Asset references must resolve under that prefix, and BUNDLE_ID
                    // changes on every deploy, so we can't bake a static URL at build
                    // time. The strategy differs between CSS and JS:
                    //
                    //  - CSS url() resolves against the stylesheet's own URL per the CSS
                    //    spec. The emitted stylesheet already lives under the bundle
                    //    prefix, so a relative URL like `url(../fonts/x.woff2)` inherits
                    //    the correct BUNDLE_ID at request time — no runtime code needed.
                    //    (Vite also rejects runtime expressions inside CSS url(), so
                    //    relative is the only option for CSS regardless.)
                    //
                    //  - JS strings have no equivalent "relative to my module" semantic
                    //    when handed to the DOM. A bare string in `href=` / `src=` would
                    //    resolve against document.baseURI — the current page URL — which
                    //    does NOT contain the bundle prefix, 404-ing the asset. And we
                    //    can't use `new URL(x, import.meta.url)` either: the SSR bundle
                    //    runs as CJS on MRT (see packageJson.type deletion below), where
                    //    import.meta.url is undefined. So JS has to produce a fully
                    //    qualified bundle-prefixed URL itself, by reading the prefix at
                    //    runtime from window._BUNDLE_PATH (client) or MRT_ENV_BASE_PATH +
                    //    BUNDLE_ID env vars (server SSR).
                    renderBuiltUrl(filename, { type, hostType }) {
                        if (mode !== 'preview' && (type === 'asset' || type === 'public')) {
                            if (hostType === 'css') {
                                return { relative: true };
                            }

                            // WARNING: This runtime code is embedded in the bundle for EVERY asset/public file.
                            // At large scale (hundreds of assets), this code snippet is duplicated hundreds of times.
                            // Keep this code as minimal as possible to avoid significant bundle size bloat.
                            const runtimeCode = `(typeof window !== 'undefined' ? window._BUNDLE_PATH : ((process.env.MRT_ENV_BASE_PATH??'')+'/mobify/bundle/'+(process.env.BUNDLE_ID??'local')+'/client/')) + ${JSON.stringify(filename)}`;

                            return {
                                runtime: runtimeCode,
                            };
                        }
                    },
                },
            };
        },
        configResolved(config) {
            resolvedConfig = config;

            // @ts-expect-error: react-router plugin context is not typed
            buildDirectory = config.__reactRouterPluginContext.reactRouterConfig.buildDirectory;
        },
        buildApp: {
            order: 'post',
            handler: async () => {
                await createManagedRuntimeBundleAssets();
            },
        },
    };
};
