/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { getMrtEntryFile } from './mrt/utils';
import type { MrtSsrConfig } from './types';

export const CARTRIDGES_BASE_DIR = 'cartridges';
export const SFNEXT_BASE_CARTRIDGE_NAME = 'app_storefrontnext_base';
export const SFNEXT_BASE_CARTRIDGE_OUTPUT_DIR = `${SFNEXT_BASE_CARTRIDGE_NAME}/cartridge/experience`;
export const SFNEXT_BASE_CARTRIDGE_VERSION = '0.0.1';

/**
 * When enabled, automatically generates and deploys cartridge metadata before an MRT push.
 * This is useful for keeping Page Designer metadata in sync with component changes.
 *
 * When enabled:
 * 1. Generates cartridge metadata from decorated components
 * 2. Deploys the cartridge to Commerce Cloud (requires dw.json configuration)
 * 3. Proceeds with the MRT push
 *
 * To enable: Set this to `true` in your local config.ts
 * Default: false (manual cartridge generation/deployment via `sfnext generate-cartridge` and `sfnext deploy-cartridge`)
 */
export const GENERATE_AND_DEPLOY_CARTRIDGE_ON_MRT_PUSH = false;

/**
 * Build MRT SSR configuration for bundle deployment
 *
 * Defines which files should be:
 * - Server-only (ssrOnly): Deployed only to Lambda functions
 * - Shared (ssrShared): Deployed to both Lambda and CDN
 *
 * @param buildDirectory - Path to the build output directory
 * @param projectDirectory - Path to the project root (reserved for future use)
 * @returns MRT SSR configuration with glob patterns
 */
export const buildMrtConfig = (_buildDirectory: string, _projectDirectory?: string): MrtSsrConfig => {
    // SSR-only files: Server bundles and entry points
    // These are deployed only to Lambda functions, not to CDN
    const ssrEntryPoint = getMrtEntryFile('production');

    const ssrOnly = [
        'server/**/*', // All server-side code
        'loader.js', // SSR entry point
        `${ssrEntryPoint}.{js,mjs,cjs}`, // SSR entry point (supports CJS and ESM formats)
        `${ssrEntryPoint}.{js,mjs,cjs}.map`, // SSR source maps
        '!static/**/*', // Exclude static assets from server
        // Include any shared server chunks prefixed with sfnext-server- (generated by the build process)
        'sfnext-server-*.mjs',
        'sfnext-server-*.mjs.map',
        // Exclude Storybook and test files
        '!**/*.stories.tsx',
        '!**/*.stories.ts',
        '!**/*-snapshot.tsx',
        '!.storybook/**/*',
        '!storybook-static/**/*',
        '!**/__mocks__/**/*',
        '!**/__snapshots__/**/*',
    ];

    // Shared files: Client bundles and static assets
    // These are deployed to both Lambda (for SSR) and CDN (for client)
    const ssrShared = [
        'client/**/*', // All client-side bundles (with content hashes)
        'static/**/*', // Static assets (images, fonts, etc.)
        '**/*.css', // Stylesheets
        '**/*.png',
        '**/*.jpg',
        '**/*.jpeg',
        '**/*.gif',
        '**/*.svg',
        '**/*.ico',
        '**/*.woff',
        '**/*.woff2',
        '**/*.ttf',
        '**/*.eot',
        // Exclude Storybook and test files
        '!**/*.stories.tsx',
        '!**/*.stories.ts',
        '!**/*-snapshot.tsx',
        '!.storybook/**/*',
        '!storybook-static/**/*',
        '!**/__mocks__/**/*',
        '!**/__snapshots__/**/*',
    ];

    // SSR function parameters
    const ssrParameters = {
        ssrFunctionNodeVersion: '24.x',
    };

    return {
        ssrOnly,
        ssrShared,
        ssrParameters,
    };
};
