/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Custom SCAPI Clients — generated by `sfnext scapi`, do not edit manually.
 */
import { type Client, type Clients, type MergeClients, type ProxyClient } from '@salesforce/storefront-next-runtime/scapi';

import type { paths as P0 } from './generated/sfnext-notify-v1';
import { operations as ops0 } from './generated/sfnext-notify-v1.operations';

export type AppClients = MergeClients<Clients, {
    sfnextNotify: ProxyClient<Client<P0>, typeof ops0>;
}>;

export const customClients = [
    { key: 'sfnextNotify', basePath: '/custom/sfnext-notify/v1', ops: ops0, locale: true, orgPrefix: true },
] as const;
